# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fib():
    '''
    Function generates Fibonacci numbers list less 4 million.
    :return: sum of the even-valued numbers
    '''
    fib_list = [0, 1]
    for i in range(100):
        if fib_list[-1] >= 4000000:
            break
        else:
            fib_list.append(fib_list[-1] + fib_list[-2])
    res = [i for i in fib_list if i % 2 == 0]
    return sum(res)


if __name__ == '__main__':
    print(fib())
